apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-service
  labels:
    {{- include "gaia.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  type: {{ .Values.gaia.service.type }} 
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.gaia.service.port }}
    targetPort: {{ .Values.gaia.service.targetPort }} 
  selector:
    {{- include "gaia.labels" . | nindent 4 }}
