apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.name" . }}-service 
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - name: database
    protocol: TCP
    port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort | default .Values.database.service.port }}
  selector:
    {{- include "database.labels" . | nindent 4 }}
