apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db.name" . }} 
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      {{- include "database.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "database.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      initContainers:
      - name: init-mongo-pv
        image: alpine:3.18.4
        imagePullPolicy: IfNotPresent
        {{- with .Values.database }}
        command:
        - sh
        - -c
        - mkdir -p {{ .volume.storagePath }} && chmod 755 {{ .volume.storagePath }}
      containers:
      - name: mongodb 
        image: {{ include "database.image" $ }}
        imagePullPolicy: {{ .image.pullPolicy }} 
        ports:
        - name: mongodb
          containerPort: 27017
        resources:
          {{- toYaml .resources | nindent 10 }}
        {{- end }}
        volumeMounts:
          {{- include "volume.mounts" . | nindent 8 }}
      volumes:
        {{- include "mongo.pvc" . | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "db.name" . }}-pvc
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
spec:
  {{- with .Values.database.volume }}
  accessModes:
    {{- toYaml .accessModes | nindent 2 }}
  storageClassName: {{ .storageClassName | quote }}
  resources:
    requests:
      storage: {{ .storage }}
  {{- end }}
  volumeName: {{ include "db.name" . }}-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "db.name" . }}-pv
spec:
  {{- with .Values.database.volume }}
  capacity:
    storage: {{ .storage }}
  accessModes:
    {{- toYaml .accessModes | nindent 2 }}
  storageClassName: {{ .storageClassName | quote }}
  hostPath:
    path: {{ .storagePath }}
  {{- end -}}
