{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.name }}-role
  labels:
    {{- include "gaia.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 0 }}
{{- end }}
