apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . | default "gaia" }}-secret 
  labels:
    {{- include "gaia.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
type: Opaque
data:
  api-password: {{ .Values.runner.password }} 
