{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "gaia.labels" . | nindent 4 }}
  annotations:
    {{- include "annotations" . | nindent 4 }}
{{- end }}
